Improved readbility
xlang-ai/OpenAgents pull request #29
Opened 2023-10-25 15:28 UTC by abhishek213-alb

Issue no #26

Fixed typos & grammatical errors

2023-10-25 15:28 UTC, abhishek213-alb commented
@BlankCheng Hello sir  I have updated it

2023-10-25 15:34 UTC, koalazf99 requested changes

2023-10-25 15:34 UTC, koalazf99 commented on README.md
> +OpenAgents can analyze data, call plugins, and  control your browser as ChatGPT Plus, but with OPEN Code for
extra space

2023-10-25 15:36 UTC, koalazf99 commented
Thank you @abhishek213-alb !!! 

As mentioned in #26 , We will handle these typo-fixing PRs in "batches" regularly to make commit history cleaner.

So you can expect this PR will be finally handled with other typo-fixing PRs together after some time.

2023-10-25 15:50 UTC, abhishek213-alb reviewed
Fixed extraspace

2023-10-25 15:52 UTC, abhishek213-alb commented
@koalazf99 sir I have fixed extra spacing

2023-10-26 04:13 UTC, abhishek213-alb commented
@BlankCheng sir can you review it

2023-10-27 06:51 UTC, closed without merging

2023-10-27 07:12 UTC, abhishek213-alb commented
@koalazf99 sir you have closed instead of merging